name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives permission to create releases and upload assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'  # Specify the Go version you want to use

      - name: Build binaries
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o feldspar-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o feldspar-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -o feldspar-windows-amd64.exe .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automatic release generated by GitHub Actions.
            This release contains pre - built binaries for multiple platforms.
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./feldspar-linux-amd64
          asset_name: feldspar-linux-amd64
          asset_content_type: application/octet - stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./feldspar-darwin-amd64
          asset_name: feldspar-darwin-amd64
          asset_content_type: application/octet - stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./feldspar-windows-amd64.exe
          asset_name: feldspar-windows-amd64.exe
          asset_content_type: application/octet - stream
